In [231]:
import numpy as np  
import pandas as pd

In [232]:
df = pd.read_csv('stroke_prediction_dataset.csv')
df

,Patient ID,Patient Name,Age,Gender,Hypertension,Heart Disease,Marital Status,Work Type,Residence Type,Average Glucose Level,...,Alcohol Intake,Physical Activity,Stroke History,Family History of Stroke,Dietary Habits,Stress Levels,Blood Pressure Levels,Cholesterol Levels,Symptoms,Diagnosis
0,18153,Mamooty Khurana,56,Male,0,1,Married,Self-employed,Rural,130.91,...,Social Drinker,Moderate,0,Yes,Vegan,3.48,140/108,"HDL: 68, LDL: 133","Difficulty Speaking, Headache",Stroke
1,62749,Kaira Subramaniam,80,Male,0,0,Single,Self-employed,Urban,183.73,...,Never,Low,0,No,Paleo,1.73,146/91,"HDL: 63, LDL: 70","Loss of Balance, Headache, Dizziness, Confusion",Stroke
2,32145,Dhanush Balan,26,Male,1,1,Married,Never Worked,Rural,189.00,...,Rarely,High,0,Yes,Paleo,7.31,154/97,"HDL: 59, LDL: 95","Seizures, Dizziness",Stroke
3,6154,Ivana Baral,73,Male,0,0,Married,Never Worked,Urban,185.29,...,Frequent Drinker,Moderate,0,No,Paleo,5.35,174/81,"HDL: 70, LDL: 137","Seizures, Blurred Vision, Severe Fatigue, Head...",No Stroke
4,48973,Darshit Jayaraman,51,Male,1,1,Divorced,Self-employed,Urban,177.34,...,Rarely,Low,0,Yes,Pescatarian,6.84,121/95,"HDL: 65, LDL: 68",Difficulty Speaking,Stroke
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,13981,Keya Iyer,88,Female,1,1,Divorced,Self-employed,Urban,160.22,...,Social Drinker,High,0,No,Paleo,1.12,171/92,"HDL: 44, LDL: 153",NaN,No Stroke
14996,87707,Anahita Virk,47,Female,0,0,Married,Private,Urban,107.58,...,Never,Low,1,No,Gluten-Free,1.47,155/71,"HDL: 35, LDL: 183",Difficulty Speaking,No Stroke
14997,33174,Ivana Kaur,35,Male,0,0,Married,Government Job,Rural,134.90,...,Rarely,High,1,No,Paleo,0.51,121/110,"HDL: 57, LDL: 159","Difficulty Speaking, Severe Fatigue, Headache",Stroke
14998,22343,Anvi Mannan,73,Male,0,0,Single,Self-employed,Urban,169.42,...,Never,High,0,Yes,Paleo,1.53,157/74,"HDL: 79, LDL: 91","Severe Fatigue, Numbness, Confusion, Dizziness...",No Stroke
14999,11066,Gokul Trivedi,64,Female,0,0,Single,Never Worked,Urban,186.88,...,Rarely,Moderate,0,No,Vegan,4.57,133/81,"HDL: 78, LDL: 179",Headache,Stroke

In [233]:
df.drop(columns=['Patient ID','Patient Name'], inplace=True)
df

,Age,Gender,Hypertension,Heart Disease,Marital Status,Work Type,Residence Type,Average Glucose Level,Body Mass Index (BMI),Smoking Status,Alcohol Intake,Physical Activity,Stroke History,Family History of Stroke,Dietary Habits,Stress Levels,Blood Pressure Levels,Cholesterol Levels,Symptoms,Diagnosis
0,56,Male,0,1,Married,Self-employed,Rural,130.91,22.37,Non-smoker,Social Drinker,Moderate,0,Yes,Vegan,3.48,140/108,"HDL: 68, LDL: 133","Difficulty Speaking, Headache",Stroke
1,80,Male,0,0,Single,Self-employed,Urban,183.73,32.57,Non-smoker,Never,Low,0,No,Paleo,1.73,146/91,"HDL: 63, LDL: 70","Loss of Balance, Headache, Dizziness, Confusion",Stroke
2,26,Male,1,1,Married,Never Worked,Rural,189.00,20.32,Formerly Smoked,Rarely,High,0,Yes,Paleo,7.31,154/97,"HDL: 59, LDL: 95","Seizures, Dizziness",Stroke
3,73,Male,0,0,Married,Never Worked,Urban,185.29,27.50,Non-smoker,Frequent Drinker,Moderate,0,No,Paleo,5.35,174/81,"HDL: 70, LDL: 137","Seizures, Blurred Vision, Severe Fatigue, Head...",No Stroke
4,51,Male,1,1,Divorced,Self-employed,Urban,177.34,29.06,Currently Smokes,Rarely,Low,0,Yes,Pescatarian,6.84,121/95,"HDL: 65, LDL: 68",Difficulty Speaking,Stroke
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,88,Female,1,1,Divorced,Self-employed,Urban,160.22,39.73,Currently Smokes,Social Drinker,High,0,No,Paleo,1.12,171/92,"HDL: 44, LDL: 153",NaN,No Stroke
14996,47,Female,0,0,Married,Private,Urban,107.58,22.17,Non-smoker,Never,Low,1,No,Gluten-Free,1.47,155/71,"HDL: 35, LDL: 183",Difficulty Speaking,No Stroke
14997,35,Male,0,0,Married,Government Job,Rural,134.90,26.38,Non-smoker,Rarely,High,1,No,Paleo,0.51,121/110,"HDL: 57, LDL: 159","Difficulty Speaking, Severe Fatigue, Headache",Stroke
14998,73,Male,0,0,Single,Self-employed,Urban,169.42,28.32,Non-smoker,Never,High,0,Yes,Paleo,1.53,157/74,"HDL: 79, LDL: 91","Severe Fatigue, Numbness, Confusion, Dizziness...",No Stroke
14999,64,Female,0,0,Single,Never Worked,Urban,186.88,39.30,Currently Smokes,Rarely,Moderate,0,No,Vegan,4.57,133/81,"HDL: 78, LDL: 179",Headache,Stroke

In [234]:
categorical_columns = df.select_dtypes(include=['object']).columns
categorical_columns

Index(['Gender', 'Marital Status', 'Work Type', 'Residence Type',
       'Smoking Status', 'Alcohol Intake', 'Physical Activity',
       'Family History of Stroke', 'Dietary Habits', 'Blood Pressure Levels',
       'Cholesterol Levels', 'Symptoms', 'Diagnosis'],
      dtype='object')

In [235]:
for i in categorical_columns:
    print(f"{df[i].nunique()} unique values in {i} column")

2 unique values in Gender column
3 unique values in Marital Status column
4 unique values in Work Type column
2 unique values in Residence Type column
3 unique values in Smoking Status column
4 unique values in Alcohol Intake column
3 unique values in Physical Activity column
2 unique values in Family History of Stroke column
7 unique values in Dietary Habits column
4458 unique values in Blood Pressure Levels column
5952 unique values in Cholesterol Levels column
5786 unique values in Symptoms column
2 unique values in Diagnosis column

In [236]:
categorical_columns_with_100_unique_values = [i for i in categorical_columns if df[i].nunique() > 100]
categorical_columns = [i for i in categorical_columns if df[i].nunique() < 100]

categorical_columns_with_100_unique_values

['Blood Pressure Levels', 'Cholesterol Levels', 'Symptoms']

In [237]:
categorical_columns.remove('Diagnosis')
categorical_columns

['Gender',
 'Marital Status',
 'Work Type',
 'Residence Type',
 'Smoking Status',
 'Alcohol Intake',
 'Physical Activity',
 'Family History of Stroke',
 'Dietary Habits']

In [238]:
df.drop(columns=categorical_columns_with_100_unique_values, inplace=True)
df.shape

(15000, 17)

In [239]:
x_df = df[df.columns[:-1]]
y_df = df[df.columns[-1]]

In [240]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
label_encoder = LabelEncoder()
onehot_encoder = OneHotEncoder()

In [241]:
x_encoded_array = onehot_encoder.fit_transform(x_df[categorical_columns]).toarray()
x_encoded_df = pd.DataFrame(x_encoded_array, columns=onehot_encoder.get_feature_names_out(categorical_columns))
y_label_encoder = label_encoder.fit_transform(y_df)

x_encoded_df.shape

(15000, 30)

In [242]:
y_encoded = label_encoder.fit_transform(y_df)
y_encoded.shape

(15000,)

In [243]:
from matplotlib import scale
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
x_encoded_df_scaled = scale.fit_transform(x_encoded_df)
x_encoded_df_scaled = pd.DataFrame(x_encoded_df_scaled, columns=x_encoded_df.columns)
x_encoded_df_scaled

,Gender_Female,Gender_Male,Marital Status_Divorced,Marital Status_Married,Marital Status_Single,Work Type_Government Job,Work Type_Never Worked,Work Type_Private,Work Type_Self-employed,Residence Type_Rural,...,Physical Activity_Moderate,Family History of Stroke_No,Family History of Stroke_Yes,Dietary Habits_Gluten-Free,Dietary Habits_Keto,Dietary Habits_Non-Vegetarian,Dietary Habits_Paleo,Dietary Habits_Pescatarian,Dietary Habits_Vegan,Dietary Habits_Vegetarian
0,-0.983864,0.983864,-0.704987,1.443566,-0.72372,-0.573245,-0.559076,-0.588950,1.700309,0.996141,...,1.414638,-0.987808,0.987808,-0.399892,-0.407375,-0.408375,-0.413694,-0.404143,2.421774,-0.41126
1,-0.983864,0.983864,-0.704987,-0.692729,1.38175,-0.573245,-0.559076,-0.588950,1.700309,-1.003874,...,-0.706895,1.012343,-1.012343,-0.399892,-0.407375,-0.408375,2.417243,-0.404143,-0.412920,-0.41126
2,-0.983864,0.983864,-0.704987,1.443566,-0.72372,-0.573245,1.788667,-0.588950,-0.588128,0.996141,...,-0.706895,-0.987808,0.987808,-0.399892,-0.407375,-0.408375,2.417243,-0.404143,-0.412920,-0.41126
3,-0.983864,0.983864,-0.704987,1.443566,-0.72372,-0.573245,1.788667,-0.588950,-0.588128,-1.003874,...,1.414638,1.012343,-1.012343,-0.399892,-0.407375,-0.408375,2.417243,-0.404143,-0.412920,-0.41126
4,-0.983864,0.983864,1.418467,-0.692729,-0.72372,-0.573245,-0.559076,-0.588950,1.700309,-1.003874,...,-0.706895,-0.987808,0.987808,-0.399892,-0.407375,-0.408375,-0.413694,2.474370,-0.412920,-0.41126
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,1.016401,-1.016401,1.418467,-0.692729,-0.72372,-0.573245,-0.559076,-0.588950,1.700309,-1.003874,...,-0.706895,1.012343,-1.012343,-0.399892,-0.407375,-0.408375,2.417243,-0.404143,-0.412920,-0.41126
14996,1.016401,-1.016401,-0.704987,1.443566,-0.72372,-0.573245,-0.559076,1.697938,-0.588128,-1.003874,...,-0.706895,1.012343,-1.012343,2.500677,-0.407375,-0.408375,-0.413694,-0.404143,-0.412920,-0.41126
14997,-0.983864,0.983864,-0.704987,1.443566,-0.72372,1.744456,-0.559076,-0.588950,-0.588128,0.996141,...,-0.706895,1.012343,-1.012343,-0.399892,-0.407375,-0.408375,2.417243,-0.404143,-0.412920,-0.41126
14998,-0.983864,0.983864,-0.704987,-0.692729,1.38175,-0.573245,-0.559076,-0.588950,1.700309,-1.003874,...,-0.706895,-0.987808,0.987808,-0.399892,-0.407375,-0.408375,2.417243,-0.404143,-0.412920,-0.41126
14999,1.016401,-1.016401,-0.704987,-0.692729,1.38175,-0.573245,1.788667,-0.588950,-0.588128,-1.003874,...,1.414638,1.012343,-1.012343,-0.399892,-0.407375,-0.408375,-0.413694,-0.404143,2.421774,-0.41126

In [244]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(x_encoded_df_scaled, y_encoded, test_size=0.33, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((10050, 30), (4950, 30), (10050,), (4950,))

In [245]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier


rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train,y_train)
rf_pred_x_encoded_test = rf.predict(X_test)
accuracy_score(y_test, rf_pred_x_encoded_test)

0.49656565656565654

In [246]:
from sklearn.linear_model import LogisticRegression


rf = LogisticRegression()
rf.fit(X_train,y_train)
rf_pred_x_encoded_test = rf.predict(X_test)
accuracy_score(y_test, rf_pred_x_encoded_test)

0.503030303030303